name: Run CI Checks

on:
  push:
    branches: [main, new]  # Trigger on push to main or new branch
  pull_request:
    branches: [main]  # Trigger on PR to main branch

jobs:
  lint:
    runs-on: ubuntu-latest  # Use Ubuntu for the CI environment
    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Check out the code from the repository

    - name: Set up Node.js
      uses: actions/setup-node@v3  # Set up Node.js environment
      with:
        node-version: '20'  # Specify the Node.js version to use

    - name: Install dependencies
      run: npm install  # Install dependencies from package.json

    - name: Run Linting
      run: npm run lint  # Run the linting command (make sure this script is in your package.json)

  test:
    runs-on: ubuntu-latest  # Use Ubuntu for the CI environment
    needs: lint  # This job depends on the lint job
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Run Tests
      run: npm run test  # Run your tests (make sure the test script exists in package.json)

  build:
    runs-on: ubuntu-latest  # Use Ubuntu for the CI environment
    needs: test  # This job depends on the test job
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Build the Project
      run: npm run build  # Run the build script, change this based on your actual build process

  deploy:
    runs-on: ubuntu-latest  # Use Ubuntu for the CI environment
    needs: build  # This job depends on the build job
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Deploy Application
      run: |
        echo "Deploying application..."
        # Add your deploy script here
        # For example: scp to a server, run docker commands, or deploy to a cloud provider
        npm run deploy  # Assuming you have a deploy script in your package.json

  # Optionally, you can add a job for notifications or additional checks:
  notify:
    runs-on: ubuntu-latest
    needs: [deploy]
    steps:
    - name: Send Notification
      run: |
        echo "Send notification to team about the deployment status"
        # Use any notification service you prefer (e.g., Slack, email, etc.)
