name: integration

on:
  pull_request:
    branches: [ "main" ]

jobs:
  test-on-node:
    name: Test on Node.js ${{ matrix.node-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Lint HTML files
        run: npm run lint:html

      - name: Lint CSS files
        run: npm run lint:css

      - name: Build the app
        run: npm run build

      - name: Run tests
        run: npm run test

      - name: Upload test coverage (if generated)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.node-version }}
          path: coverage/
